In [14]:
import pandas as pd
# Load the dataset
df = pd.read_csv('Desktop/3MTT/Superstore csv.csv', encoding= 'latin1')

In [15]:
df.head(5)

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
0,1,3,13/10/2010,Low,6,261.5400,0.04,Regular Air,-213.25,38.94,...,Muhammed MacIntyre,Nunavut,East,Small Business,Office Supplies,Storage & Organization,"Eldon Base for stackable storage shelf, platinum",Large Box,0.80,20/10/2010
1,49,293,1/10/2012,High,49,10123.0200,0.07,Delivery Truck,457.81,208.16,...,Barry French,Nunavut,East,Consumer,Office Supplies,Appliances,"1.7 Cubic Foot Compact ""Cube"" Office Refrigera...",Jumbo Drum,0.58,2/10/2012
2,50,293,1/10/2012,High,27,244.5700,0.01,Regular Air,46.71,8.69,...,Barry French,Nunavut,East,Consumer,Office Supplies,Binders and Binder Accessories,"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl",Small Box,0.39,3/10/2012
3,80,483,10/7/2011,High,30,4965.7595,0.08,Regular Air,1198.97,195.99,...,Clay Rozendal,Nunavut,East,Corporate,Technology,Telephones and Communication,R380,Small Box,0.58,12/7/2011
4,85,515,28/8/2010,Not Specified,19,394.2700,0.08,Regular Air,30.94,21.78,...,Carlos Soltero,Nunavut,East,Consumer,Office Supplies,Appliances,Holmes HEPA Air Purifier,Medium Box,0.50,30/8/2010

In [18]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Order Priority', 'Order Quantity',
       'Sales', 'Discount', 'Ship Mode', 'Profit', 'Unit Price',
       'Shipping Cost', 'Customer Name', 'Province', 'Region',
       'Customer Segment', 'Product Category', 'Product Sub-Category',
       'Product Name', 'Product Container', 'Product Base Margin',
       'Ship Date'],
      dtype='str')

In [22]:
#selecting columns
df[[ 'Order ID', 'Customer Name']]

      Order ID       Customer Name
0            3  Muhammed MacIntyre
1          293        Barry French
2          293        Barry French
3          483       Clay Rozendal
4          515      Carlos Soltero
...        ...                 ...
8394     55558          Mick Brown
8395     55558          Mick Brown
8396     56550        Frank Hawley
8397     56550        Frank Hawley
8398     56581     Grant Donatelli

[8399 rows x 2 columns]

In [23]:
#Filtering Data (Where)
df[df['Region']=='West']

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
735,8263,59074,12/8/2010,Low,37,589.6300,0.03,Regular Air,70.80,14.98,...,Jack Lebron,British Columbia,West,Corporate,Furniture,Office Furnishings,"GE 4 Foot Flourescent Tube, 40 Watt",Small Pack,0.39,14/8/2010
736,8292,59233,20/8/2010,High,3,336.8400,0.08,Delivery Truck,-160.46,100.98,...,Jack Lebron,British Columbia,West,Corporate,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Fully Ass...",Jumbo Box,0.62,22/8/2010
737,8293,59233,20/8/2010,High,30,397.1700,0.10,Express Air,7.69,14.34,...,Jack Lebron,British Columbia,West,Corporate,Furniture,Office Furnishings,Nu-Dell Leatherette Frames,Small Pack,0.49,20/8/2010
738,8316,59425,17/5/2012,Medium,24,2094.1200,0.00,Regular Air,717.12,83.10,...,Giulietta Baptist,British Columbia,West,Home Office,Technology,Computer Peripherals,Micro Innovations Micro Digital Wireless Keybo...,Small Box,0.45,19/5/2012
739,8317,59425,17/5/2012,Medium,46,1714.0200,0.04,Regular Air,741.27,37.94,...,Giulietta Baptist,British Columbia,West,Home Office,Office Supplies,Paper,Snap-A-Way® Black Print Carbonless Ruled Speed...,Wrap Bag,0.38,20/5/2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8394,7765,55558,9/8/2010,Medium,8,1294.0400,0.05,Delivery Truck,-323.18,150.98,...,Mick Brown,Alberta,West,Consumer,Furniture,Bookcases,Bush Mission Pointe Library,Jumbo Box,0.65,9/8/2010
8395,7766,55558,9/8/2010,Medium,23,392.5700,0.04,Regular Air,22.25,17.07,...,Mick Brown,Alberta,West,Consumer,Office Supplies,Envelopes,Recycled Interoffice Envelopes with Re-Use-A-S...,Small Box,0.38,11/8/2010
8396,7906,56550,8/4/2011,Not Specified,37,823.7800,0.03,Express Air,343.05,22.23,...,Frank Hawley,Alberta,West,Home Office,Furniture,Office Furnishings,"Executive Impressions 14""",Small Pack,0.41,10/4/2011
8397,7907,56550,8/4/2011,Not Specified,8,469.8375,0.00,Regular Air,-159.24,65.99,...,Frank Hawley,Alberta,West,Home Office,Technology,Telephones and Communication,Talkabout T8367,Small Box,0.56,9/4/2011
8398,7914,56581,8/2/2009,High,20,2026.0100,0.10,Express Air,580.43,105.98,...,Grant Donatelli,Alberta,West,Consumer,Furniture,Office Furnishings,"Tenex 46"" x 60"" Computer Anti-Static Chairmat,...",Medium Box,0.65,11/2/2009

In [24]:
#Sorting Data ( Order By)
df.sort_values(by='Sales',ascending= False)

,Row ID,Order ID,Order Date,Order Priority,Order Quantity,Sales,Discount,Ship Mode,Profit,Unit Price,...,Customer Name,Province,Region,Customer Segment,Product Category,Product Sub-Category,Product Name,Product Container,Product Base Margin,Ship Date
4674,4190,29766,21/3/2009,Medium,13,89061.05,0.00,Regular Air,27220.69,6783.02,...,Emily Phan,New Brunswick,East,Consumer,Technology,Office Machines,Polycom ViewStation ISDN Videoconferencing Unit,Large Box,0.39,22/3/2009
3512,452,3073,7/1/2009,Medium,7,45923.76,0.07,Regular Air,102.61,6783.02,...,Jasper Cacioppo,Quebec,Central,Home Office,Technology,Office Machines,Polycom ViewStation ISDN Videoconferencing Unit,Large Box,0.39,8/1/2009
5861,4264,30343,21/5/2012,Critical,8,41343.21,0.09,Regular Air,3852.19,6783.02,...,Craig Carreira,Saskachewan,South,Corporate,Technology,Office Machines,Polycom ViewStation ISDN Videoconferencing Unit,Large Box,0.39,23/5/2012
3572,2026,14435,1/12/2012,Not Specified,9,33367.85,0.01,Regular Air,3992.52,3499.99,...,Dennis Kane,Quebec,Central,Small Business,Technology,Copiers and Fax,Canon imageCLASS 2200 Advanced Copier,Large Box,0.37,4/12/2012
6995,4629,32932,9/1/2010,Low,49,29884.60,0.05,Regular Air,12748.86,599.99,...,Karen Carlisle,British Columbia,West,Corporate,Technology,Copiers and Fax,Canon Image Class D660 Copier,Large Box,0.44,13/1/2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3343,1314,9635,13/4/2009,Critical,1,3.42,0.05,Regular Air,-2.91,1.88,...,Andy Reiter,Quebec,Central,Corporate,Office Supplies,Binders and Binder Accessories,Staples® General Use 3-Ring Binders,Small Box,0.37,15/4/2009
7224,6987,49925,22/1/2010,High,1,3.41,0.06,Regular Air,-1.78,2.88,...,Adam Hart,British Columbia,West,Corporate,Office Supplies,Pens & Art Supplies,Newell 346,Wrap Bag,0.56,23/1/2010
6495,3263,23361,3/7/2010,Critical,2,3.23,0.06,Regular Air,-2.73,1.26,...,Benjamin Patterson,Yukon,South,Corporate,Office Supplies,Rubber Bands,Bagged Rubber Bands,Wrap Bag,0.81,4/7/2010
7661,3553,25318,19/11/2011,Critical,1,3.20,0.09,Regular Air,-3.16,1.88,...,Ken Dana,Alberta,West,Small Business,Office Supplies,Binders and Binder Accessories,Staples® General Use 3-Ring Binders,Small Box,0.37,21/11/2011
1066,889,6374,7/8/2011,Critical,1,2.24,0.01,Regular Air,-1.97,1.48,...,Ricardo Emerson,British Columbia,West,Corporate,Office Supplies,Rubber Bands,Binder Clips by OIC,Wrap Bag,0.37,9/8/2011

In [27]:
# Aggregating data
df.groupby('Ship Mode')['Order Quantity'].sum()

Ship Mode
Delivery Truck     28764
Express Air        25353
Regular Air       160660
Name: Order Quantity, dtype: int64